### ISSUE TITLE
Error reading: read tcp 127.0.0.1:51052->127.0.0.1:1337: i/o timeout

### ISSUE THREAD

**Issue by gulsennihat** [markwinter/go-finproto#4]
hello,

I'm getting this error when I run server and client. Could you please help me this error?

server:
2024/07/24 00:35:34 Listening on 127.0.0.1:1337
2024/07/24 00:35:41 client connected "127.0.0.1:51774"
2024/07/24 00:35:41 starting seq for client "127.0.0.1:51774" is 1
2024/07/24 00:35:41 login accepted sending successful
2024/07/24 00:35:43 client connected "127.0.0.1:51775"
2024/07/24 00:35:43 starting seq for client "127.0.0.1:51775" is 1
2024/07/24 00:35:43 login accepted sending successful
2024/07/24 00:35:45 client connected "127.0.0.1:51776"

client:
 2024/07/24 00:35:41 connected to session "ABCDEFGHIJ" and starting with sequence 1
2024/07/24 00:35:41 logged in
2024/07/24 00:35:43 Error reading: read tcp 127.0.0.1:51774->127.0.0.1:1337: i/o timeout
2024/07/24 00:35:43 connection error, attempting to relogin to session "ABCDEFGHIJ" with sequence number 1
2024/07/24 00:35:43 connected to session "ABCDEFGHIJ" and starting with sequence 1
2024/07/24 00:35:45 Error reading: read tcp 127.0.0.1:51775->127.0.0.1:1337: i/o timeout
2024/07/24 00:35:45 connection error, attempting to relogin to session "ABCDEFGHIJ" with sequence number 1
2024/07/24 00:35:45 connected to session "ABCDEFGHIJ" and starting with sequence 1
2024/07/24 00:35:47 Error reading: read tcp 127.0.0.1:51776->127.0.0.1:1337: i/o timeout

Thank you.

**Comment by markwinter** [comment]
@gulsennihat Thanks for the report, will take a look

**Comment by markwinter** [comment]
@gulsennihat This is happening because I was in the middle of re-implementing the Server so it doesn't currently send any data atm and just timesout.

The client should be in a working state though.
