### ISSUE TITLE
itch: excessive logging ?

### ISSUE THREAD

**Issue by pgalbavy-itrs** [markwinter/go-finproto#5]
Just playing at the moment, but the log messages in the main Parse...() calls seem excessive. Typically an imported package shouldn't do it's own logging, should it?

I know I can fork and remove the log lines but perhaps a better way could be found?

**Comment by markwinter** [comment]
@pgalbavy-itrs

Hello yes you're right generally a library shouldn't be logging, or should at least should accept some logger from the user. I'll make some changes

**Comment by markwinter** [comment]
@pgalbavy-itrs Thanks for the report. I've removed logging from the itch package now
